#!/bin/bash
verif_ptrs() {
    # 'porta' (puerto) en español.
    puerto=$1
    # Obtiene puertos en estado LISTEN, excluyendo ESTABLISHED y el encabezado COMMAND.
    PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND" | grep "LISTEN")
    # Itera sobre los puertos que están en escucha (LISTEN)
    for pton in $(echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq); do
        # Obtiene los servicios que están usando ese puerto
        svcs=$(echo -e "$PT" | grep -w "$pton" | awk '{print $1}' | uniq)
        [[ "$puerto" = "$pton" ]] && {
            # Mensaje de puerto en uso
            echo -e "\n\033[1;31mPUERTO \033[1;33m$puerto \033[1;31mEN USO POR \033[1;37m$svcs\033[0m"
            sleep 3
            fun_initcheck
        }
    done
}

fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim # 'fim' (fin)
        [[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
        ${comando[0]} >/dev/null 2>&1
        ${comando[1]} >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    # Mensaje de espera
    echo -ne "\033[1;33mESPERE \033[1;37m- \033[1;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;31m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[1;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        # Mensaje de espera
        echo -ne "\033[1;33mESPERE \033[1;37m- \033[1;33m["
    done
    # Mensaje de OK
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}

fun_initcheck() {
    clear
    # Encabezado del menú
    echo -e "\E[44;1;37m           ADMINISTRAR CHECKUSER V4           \E[0m"
    echo ""
    var_sks1=$(ps x | grep "checkuser" | grep -v grep >/dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
    var_sks2=$(ps x | grep "4gcheck" | grep -v grep >/dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
    var_sks3=$(ps x | grep "5gcheck" | grep -v grep >/dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
    echo ""
    # Opciones del menú
    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mACTIVAR CHECKUSER(ESTÁNDAR) $var_sks1 \033[0m" # PADRÃO -> ESTÁNDAR
    echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mACTIVAR CHECKUSER(CONECTA4G) $var_sks2 \033[0m"
    echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mACTIVAR CHECKUSER(CONECTA5G MOD FATHER) $var_sks3 \033[0m"
    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLVER\033[0m"
    echo ""
    # Solicitud de respuesta
    echo -ne "\033[1;32m¿QUÉ DESEA HACER \033[1;33m?\033[1;37m "
    read resposta # 'resposta' (respuesta)
    if [[ "$resposta" = '1' ]]; then
        if ps x | grep -w checkuser | grep -v grep 1>/dev/null 2>/dev/null; then
            clear
            # Encabezado de desactivación
            echo -e "\E[41;1;37m             CHECKUSER(ESTÁNDAR)              \E[0m"
            echo ""
            fun_stopbad() {
                screen -r -S "checkuser" -X quit
                [[ $(grep -wc "check.py" /etc/autostart) != '0' ]] && {
                    sed -i '/check.py/d' /etc/autostart
                }
                sleep 1
                screen -wipe >/dev/null
            }
            # Mensaje de desactivación
            echo -e "\033[1;32mDESACTIVANDO EL CHECKUSER(ESTÁNDAR)\033[1;33m"
            echo ""
            fun_stopbad
            echo ""
            # Mensaje de éxito
            echo -e "\033[1;32mCHECKUSER(ESTÁNDAR) DESACTIVADO CON ÉXITO!\033[1;33m"
            sleep 3
            fun_initcheck
        else
            clear
            # Encabezado de activación
            echo -e "\E[44;1;37m           ACTIVACIÓN DE CHECKUSER(ESTÁNDAR)            \E[0m"
            echo ""
            # Solicitud de puerto
            echo -ne "\033[1;32m¿QUÉ PUERTO DESEA UTILIZAR \033[1;33m?\033[1;37m: " # ULTILIZAR -> UTILIZAR
            read porta # 'porta' (puerto)
            [[ $porta != ?(+|-)+([0-9]) ]] && {
                echo ""
                # Mensaje de puerto inválido
                echo -e "\033[1;31m¡Puerto inválido!" # invalida -> inválido
                sleep 3
                clear
                fun_initcheck
            }
            verif_ptrs $porta # Se mantiene el nombre de la función
            fun_check() {
                screen -dmS checkuser python3 /etc/SSHPlus/check.py $porta 1
                [[ $(grep -wc "check.py" /etc/autostart) = '0' ]] && {
                    echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SSHPlus/check.py $porta 1; }" >>/etc/autostart
                } || {
                    sed -i '/check.py/d' /etc/autostart
                    echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SSHPlus/check.py $porta 1; }" >>/etc/autostart
                }
                sleep 1
            }

            fun_check2() {
                screen -dmS checkuser python3 /etc/SSHPlus/check.py $porta 2
                [[ $(grep -wc "check.py" /etc/autostart) = '0' ]] && {
                    echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SSHPlus/check.py $porta 2; }" >>/etc/autostart
                } || {
                    sed -i '/check.py/d' /etc/autostart
                    echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SSHPlus/check.py $porta 2; }" >>/etc/autostart
                }
                sleep 1
            }
            echo ""
            # Solicitud de formato
            echo -e "\033[1;32m¿QUÉ FORMATO DESEA UTILIZAR? \033[1;33m?\033[1;37m: " # ULTILIZAR -> UTILIZAR
            # Advertencias
            echo -e "\033[1;31mEL FORMATO DE LA FECHA PUEDE VARIAR DEPENDIENDO DE LA PROGRAMACIÓN DE SU APLICACIÓN.\033[0m" # PODE VARIAR DEPENDENDO DA PROGRAMAÇÃO DO SEU APLICATIVO -> PUEDE VARIAR DEPENDIENDO DE LA PROGRAMACIÓN DE SU APLICACIÓN
            echo -e "\033[1;31mSELECCIONE EL FORMATO CONFORME A SU NECESIDAD.\033[0m" # CONFORME A SUA NECESSIDADE -> CONFORME A SU NECESIDAD
            echo ""
            # Opciones de formato
            echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mFORMATO YYYY/MM/DD (MÁS COMÚN)\033[0m" # MAIS COMUN -> MÁS COMÚN
            echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mFORMATO DD/MM/YYYY\033[0m"
            echo ""
            echo -ne "\033[1;36mOpción: \033[1;37m" # Opção -> Opción
            read resposta
            if [[ "$resposta" = '1' ]]; then
                echo ""
                fun_bar 'fun_check'
            elif [[ "$resposta" = '2' ]]; then
                echo ""
                fun_bar 'fun_check2'
            else
                echo ""
                # Opción inválida
                echo -e "\033[1;31m¡Opción inválida!\033[0m" # Opcao invalida -> Opción inválida
                sleep 3
                fun_initcheck
            fi
            echo ""
            # Éxito de activación
            echo -e "\033[1;32mCHECKUSER(ESTÁNDAR) ACTIVADO CON ÉXITO\033[1;33m" # ATIVADO COM SUCESSO -> ACTIVADO CON ÉXITO
            echo ""
            #IP=$(cat /etc/IP)
            IP=$(curl -s icanhazip.com)
            echo "URL: http://$IP:$porta/checkUser"
            echo ""
            # Mensaje para continuar
            echo -ne "\033[1;36mPresione para continuar: \033[1;37m" # Pressione para continuar -> Presione para continuar
            read x
            fun_initcheck
        fi
    elif [[ "$resposta" = '2' ]]; then
        if ps x | grep -w 4gcheck | grep -v grep 1>/dev/null 2>/dev/null; then
            clear
            # Encabezado de desactivación
            echo -e "\E[41;1;37m             CHECKUSER(CONECTA4G)              \E[0m"
            echo ""
            fun_stopbad() {
                screen -r -S "4gcheck" -X quit
                [[ $(grep -wc "4gcheck.py" /etc/autostart) != '0' ]] && {
                    sed -i '/4gcheck.py/d' /etc/autostart
                }
                sleep 1
                screen -wipe >/dev/null
            }
            # Mensaje de desactivación
            echo -e "\033[1;32mDESACTIVANDO EL CHECKUSER(CONECTA4G)\033[1;33m"
            echo ""
            fun_stopbad
            echo ""
            # Mensaje de éxito
            echo -e "\033[1;32mCHECKUSER(CONECTA4G) DESACTIVADO CON ÉXITO!\033[1;33m"
            sleep 1
            fun_initcheck
        else
            clear
            # Encabezado de activación
            echo -e "\E[44;1;37m           ACTIVACIÓN DE CHECKUSER(CONECTA4G)           \E[0m"
            echo ""
            # Solicitud de puerto
            echo -ne "\033[1;32m¿QUÉ PUERTO DESEA UTILIZAR \033[1;33m?\033[1;37m: "
            read porta
            [[ $porta != ?(+|-)+([0-9]) ]] && {
                echo ""
                # Puerto inválido
                echo -e "\033[1;31m¡Puerto inválido!"
                sleep 3
                clear
                fun_initcheck
            }
            verif_ptrs $porta

            fun_udpon() {
                screen -dmS 4gcheck python3 /etc/SSHPlus/4gcheck.py $porta
                [[ $(grep -wc "4gcheck.py" /etc/autostart) = '0' ]] && {
                    echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SSHPlus/4gcheck.py $porta; }" >>/etc/autostart
                } || {
                    sed -i '/check.py/d' /etc/autostart
                    echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SSHPlus/4gcheck.py $porta; }" >>/etc/autostart
                }
                sleep 1
            }
            echo ""
            fun_bar 'fun_udpon'
            echo ""
            # Éxito de activación
            echo -e "\033[1;32mCHECKUSER(ESTÁNDAR) ACTIVADO CON ÉXITO\033[1;33m"
            echo ""
            #IP=$(cat /etc/IP)
            IP=$(curl -s icanhazip.com)
            echo "URL: http://$IP:$porta/checkUser"
            echo ""
            # Mensaje para continuar
            echo -ne "\033[1;36mPresione para continuar: \033[1;37m"
            read x
            fun_initcheck
        fi

    elif [[ "$resposta" = '3' ]]; then
        # Llamar al script checkuserMenu.sh
        bash /root/checkuser/checkuserMenu.sh # Substitua pelo caminho correto -> Sustituya por la ruta correcta


    elif [[ "$resposta" = '0' ]]; then
        echo ""
        # Retornando
        echo -e "\033[1;31mVolviendo...\033[0m" # Retornando -> Volviendo
        sleep 1
        menu
    else
        echo ""
        # Opción inválida
        echo -e "\033[1;31m¡Opción inválida!\033[0m"
        sleep 1
        fun_initcheck
    fi
}

inst_depedencias() {
    # Verificar si pip3 está instalado
    if ! [ -x "$(command -v pip3)" ]; then
        echo 'Error: pip3 no está instalado.' >&2 # não está instalado -> no está instalado
        echo 'Instale pip3 y ejecute el script nuevamente.' >&2 # Instale pip3 e execute o script novamente -> Instale pip3 y ejecute el script nuevamente

        if ! apt-get install -y python3-pip; then
            echo 'Error al instalar pip3' >&2 # Erro ao instalar pip3 -> Error al instalar pip3
            exit 1
        else
            echo 'Instalado pip3 con éxito' # Instalado pip3 com sucesso -> Instalado pip3 con éxito
        fi
    fi

    # instalar flask
    pip3 install flask >/dev/null 2>&1

    # instalar python3
    apt install python3

    # descargar check.py
    [[ -e "/etc/SSHPlus/check.py" ]] && {
        sleep 0.1
    } || {
        cd $HOME
        wget https://raw.githubusercontent.com/modderajuda/Sshplus25/main/M/check.py -o /dev/null
        mv -f $HOME/check.py /etc/SSHPlus/check.py
    }

    [[ -e "/etc/SSHPlus/4gcheck.py" ]] && {
        sleep 0.1
    } || {
        cd $HOME
        wget https://raw.githubusercontent.com/modderajuda/Sshplus25/main/M/4gcheck.py -o /dev/null
        mv -f $HOME/4gcheck.py /etc/SSHPlus/4gcheck.py
    }

    [[ -e "/bin/check" ]] && {
        sleep 0.1
    } || {
        cd $HOME
        wget https://raw.githubusercontent.com/modderajuda/Sshplus25/main/M/check -o /dev/null
        mv -f $HOME/check /bin/check
        chmod 777 /bin/check
    }

    [[ -e "/root/checkuser/checkuserMenu.sh" ]] && {
        sleep 0.1
    } || {
        cd $HOME
        sudo kill -9 $(lsof -t -i:5454)
        pkill -9 -f "/root/checkuser/checkuser.py"
        git clone https://github.com/modderajuda/checkuser.git
        chmod +x /root/checkuser/checkuserMenu.sh
        mv -f $HOME/checkuserMenu.sh /root/checkuser/checkuserMenu.sh
        chmod 777 /root/checkuser/checkuserMenu.sh
    }


}


[[ -e "/etc/SSHPlus/check.py" ]] && [[ -e "/etc/SSHPlus/4gcheck.py" ]] && [[ -e "/bin/check" ]] && {
    fun_initcheck
} || {
    clear
    # Encabezado del instalador
    echo -e "\E[44;1;37m          INSTALADOR CHECKUSER             \E[0m"
    # Mensaje de advertencia
    echo -e "\n\033[1;33m¡ESTÁS A PUNTO DE INSTALAR CHECKUSER!\033[0m" # VC ESTA PRESTES A INSTALAR O CHECKUSER -> ESTÁS A PUNTO DE INSTALAR CHECKUSER
    echo ""
    # Solicitud de confirmación
    echo -ne "\033[1;32m¿DESEAS CONTINUAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m " # DESEJA CONTINUAR -> ¿DESEAS CONTINUAR
    read resposta
    [[ "$resposta" = 's' ]] && {
        clear
        # Encabezado de instalación
        echo -e "\E[41;1;37m             INSTALANDO CHECKUSER...              \E[0m"
        echo ""
        fun_bar 'inst_depedencias'
        # Éxito de instalación
        echo -e "\033[1;32mCHECKUSER INSTALADO\033[1;33m"
        sleep 3
        fun_initcheck
    } || {
        # Volviendo
        echo -e "\n\033[1;31mVolviendo...\033[0m"
        sleep 2
        clear
        menu
    }
}
